### ISSUE TITLE
Best Practice: Addressing local modifications to settings.php file(s)

### ISSUE THREAD

**Issue by deadarm** [palantirnet/the-build#88]
## Issue
After switching branches locally there are changes to settings.php, settings.acquia.php, and settings.dev.php etc. that can not be git checked out without using sudo. This issue can compound when working on multisites. The error is: `unable to unlink old 'docroot/sites/default/settings.php': Permission denied`

## Possible solutions

@biz123 has been using chmod 777 on the files and then git stashing them.
@patrickfweston suggests running `phing build` so the permissions reset and then you can normally run `git checkout -- docroot/sites/default/settings.php` to reset it.
I have been sudo stashing or checking out the files which is tedious.

## Question
1. What is the best way to address settings.php's local modifications when I switch from a feature branch to develop?
2. Is there a more permanent fix to address this issue?

**Comment by becw** [comment]
Whew, this is an old question, sorry!

I think this happens because for certain Drush actions, Drush or Drupal will chmod the site directory (e.g. `web/sites/default/`) for security reasons. When the `settings.php` file is committed to the repository, you'll get the permissions errors that you describe. This isn't something that the-build can prevent.

There are a couple things you can do to mitigate this issue:

* Don't check the `settings.php` file (or any files in `web/sites/default/`) in to git. By default, this is the way the-build is set up -- instead of being checked in to git, the `settings.php` file is generated during `phing build` from the template at `conf/drupal/settings.php`. Sites that check in all of their dependencies, or sites that use the versions of the `settings.php` file provided by Pantheon or Platform.sh will not be able to use this approach.
* You can fix the permissions on the site directory and reset the files each time you run into the issue.
  1. `chmod 755 web/sites/default`
  2. ` git checkout -- web/sites/default`
* You can run `phing build`. Because these directories need to be writable in order to install Drupal, the default build task includes chmod-ing them.

**Comment by becw** [comment]
This should be resolved by the 2.0 release -- the-build no longer writes the `settings.php` file on `phing build`, instead it writes a `settings.*.php` file.
